
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(40) DEFAULT NULL,
  `email` varchar(40) NOT NULL,
  `password` varchar(40) DEFAULT NULL,
  `role` varchar(20) DEFAULT NULL,
  `status` varchar(20) DEFAULT 'active',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1

CREATE TABLE `customer` (
  `CUST_ID` int(11) NOT NULL,
  `CUST_NAME` varchar(32) DEFAULT NULL,
  `CUST_DOB` date DEFAULT NULL,
  `CUST_ADDR` varchar(128) DEFAULT NULL,
  `CUST_EMAIL` varchar(64) DEFAULT NULL,
  `CUST_TEL` varchar(16) DEFAULT NULL,
  `CUST_JOINDATE` datetime DEFAULT NULL,
  `CUST_LASTACCESS` date DEFAULT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8

CREATE TABLE `buildbook` (
  `book_id` int(11) NOT NULL AUTO_INCREMENT,
  `status` varchar(20) DEFAULT 'active',
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `build_date` date DEFAULT NULL,
  `build_by` varchar(100) DEFAULT NULL,
  `adv_config_date` timestamp NULL DEFAULT NULL,
  `adv_config_by` varchar(100) DEFAULT NULL,
  `val_config_date` timestamp NULL DEFAULT NULL,
  `val_config_by` varchar(100) DEFAULT NULL,
  `customer_name` varchar(100) DEFAULT NULL,
  `customer_sponsor` varchar(100) DEFAULT NULL,
  `account_excutive` varchar(100) DEFAULT NULL,
  `program_manager` varchar(100) DEFAULT NULL,
  `project_manager` varchar(100) DEFAULT NULL,
  `partner` varchar(100) DEFAULT NULL,
  `build_engr` varchar(100) DEFAULT NULL,
  `validation_engr` varchar(100) DEFAULT NULL,
  `site` varchar(100) DEFAULT NULL,
  `cluster_type` varchar(100) DEFAULT NULL,
  `cluster_name` varchar(100) DEFAULT NULL,
  `cluster_owner` varchar(100) DEFAULT NULL,
  `node_count` varchar(100) DEFAULT NULL,
  `hardware_model` varchar(100) DEFAULT NULL,
  `ip_address` mediumblob,
  `firewall_roles` varchar(10) DEFAULT 'yes',
  `hypervisor_type` varchar(100) DEFAULT NULL,
  `v_center_name` varchar(100) DEFAULT NULL,
  `nx_cluster_ip` varchar(100) DEFAULT NULL,
  `nx_license_ver` varchar(100) DEFAULT NULL,
  `cluster_redun_factor` varchar(100) DEFAULT NULL,
  `storage_cont_name` varchar(100) DEFAULT NULL,
  `storange_cont_size` varchar(100) DEFAULT NULL,
  `foundation_version` varchar(100) DEFAULT NULL,
  `aos_version` varchar(100) DEFAULT NULL,
  `ncc_version` varchar(100) DEFAULT NULL,
  `spp_version` varchar(100) DEFAULT NULL,
  `nx_firmware` varchar(100) DEFAULT NULL,
  `lcm_site` varchar(100) DEFAULT NULL,
  `storage_repl_facotr` varchar(100) DEFAULT NULL,
  `compression_setting` varchar(100) DEFAULT NULL,
  `eraure_coding` varchar(100) DEFAULT NULL,
  `deduplication` varchar(100) DEFAULT NULL,
  `reserver_comp_setting` varchar(100) DEFAULT NULL,
  `dns_server1` varchar(100) DEFAULT NULL,
  `dns_server2` varchar(100) DEFAULT NULL,
  `ntp_server1` varchar(100) DEFAULT NULL,
  `ntp_sercer2` varchar(100) DEFAULT NULL,
  `ntp_server3` varchar(100) DEFAULT NULL,
  `proxy_addr` varchar(100) DEFAULT NULL,
  `proxy_port` varchar(100) DEFAULT NULL,
  `proxy_user` varchar(100) DEFAULT NULL,
  `proxy_password` varchar(100) DEFAULT NULL,
  `proxy_protocol` varchar(100) DEFAULT NULL,
  `auth_name` varchar(100) DEFAULT NULL,
  `auth_domain` varchar(100) DEFAULT NULL,
  `auth_url` varchar(100) DEFAULT NULL,
  `auth_serv_account` varchar(100) DEFAULT NULL,
  `auth_serv_acc_password` varchar(100) DEFAULT NULL,
  `local_username` varchar(100) DEFAULT NULL,
  `local_fname` varchar(100) DEFAULT NULL,
  `local_lname` varchar(100) DEFAULT NULL,
  `local_email` varchar(100) DEFAULT NULL,
  `local_password` varchar(100) DEFAULT NULL,
  `local_roles` varchar(100) DEFAULT NULL,
  `language` varchar(100) DEFAULT NULL,
  `hypervisor_password` varchar(100) DEFAULT NULL,
  `cvm_password` varchar(100) DEFAULT NULL,
  `ipmi_password` varchar(100) DEFAULT NULL,
  `admin_password` varchar(100) DEFAULT NULL,
  `nutanix_password` varchar(100) DEFAULT NULL,
  `vm_cluster_name` varchar(100) DEFAULT NULL,
  `vm_ha` varchar(100) DEFAULT NULL,
  `vm_drs` varchar(100) DEFAULT NULL,
  `vm_esxi_version` varchar(100) DEFAULT NULL,
  `vm_esxi_plevel` varchar(100) DEFAULT NULL,
  `vm_dns_server1` varchar(100) DEFAULT NULL,
  `vm_dns_server2` varchar(100) DEFAULT NULL,
  `vm_ntp_server1` varchar(100) DEFAULT NULL,
  `vm_ntp_server2` varchar(100) DEFAULT NULL,
  `vm_ntp_server3` varchar(100) DEFAULT NULL,
  `vm_automation_level` varchar(100) DEFAULT NULL,
  `vm_restart_priority` varchar(100) DEFAULT NULL,
  `vm_start_next_prio` varchar(100) DEFAULT NULL,
  `vm_port_group_name` varchar(100) DEFAULT NULL,
  `vm_port_group_net` varchar(100) DEFAULT NULL,
  `vm_vmotion` varchar(100) DEFAULT NULL,
  `vm_vmotion_port_name` varchar(100) DEFAULT NULL,
  `vm_vmotion_port_net` varchar(100) DEFAULT NULL,
  `ahv_port_group_name` varchar(100) DEFAULT NULL,
  `ahv_vlan_ip` varchar(100) DEFAULT NULL,
  `prism_ip` varchar(100) DEFAULT NULL,
  `prism_user` varchar(100) DEFAULT NULL,
  `prism_password` varchar(100) DEFAULT NULL,
  `prism_smtp_name` varchar(100) DEFAULT NULL,
  `prism_smtp_port` varchar(100) DEFAULT NULL,
  `prism_smtp_addr` varchar(100) DEFAULT NULL,
  `prism_smtp_smode` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`book_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
